name: ESLint
on: push

env:
  NODE_VERSION: 18

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci

    - name: Code Linting
      run: npm run lint


